
str_constants = {
    'SDL_': [
        "HINT_RENDER_VSYNC",
        "HINT_RENDER_SCALE_QUALITY",
        "HINT_VIDEO_X11_NET_WM_PING",
        "HINT_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK",
    ]
}

int_constants = {
    'SDL_': [      # constants with the 'SDL_' prefix in C
        "MAJOR_VERSION",
        "MINOR_VERSION",
        "PATCHLEVEL",

        "TRUE",
        "FALSE",
        "DISABLE",
        "ENABLE",
        "IGNORE",

        "SWSURFACE",
        "RLEACCEL",
        "PREALLOC",

        "WINDOWPOS_UNDEFINED",
        "WINDOWPOS_CENTERED",

        "WINDOW_FULLSCREEN",
        "WINDOW_FULLSCREEN_DESKTOP",
        "WINDOW_OPENGL",
        "WINDOW_SHOWN",
        "WINDOW_HIDDEN",
        "WINDOW_BORDERLESS",
        "WINDOW_RESIZABLE",
        "WINDOW_MINIMIZED",
        "WINDOW_MAXIMIZED",
        "WINDOW_INPUT_GRABBED",
        "WINDOW_ALLOW_HIGHDPI",

        "RENDERER_SOFTWARE",
        "RENDERER_ACCELERATED",
        "RENDERER_PRESENTVSYNC",
        "RENDERER_TARGETTEXTURE",

        "GL_RED_SIZE",
        "GL_GREEN_SIZE",
        "GL_BLUE_SIZE",
        "GL_ALPHA_SIZE",
        "GL_BUFFER_SIZE",
        "GL_DOUBLEBUFFER",
        "GL_DEPTH_SIZE",
        "GL_STENCIL_SIZE",
        "GL_ACCUM_RED_SIZE",
        "GL_ACCUM_GREEN_SIZE",
        "GL_ACCUM_BLUE_SIZE",
        "GL_ACCUM_ALPHA_SIZE",
        "GL_STEREO",              #if SDL_VERSION_ATLEAST(1, 2, 5)
        "GL_MULTISAMPLEBUFFERS",  #if SDL_VERSION_ATLEAST(1, 2, 6)
        "GL_MULTISAMPLESAMPLES",  #if SDL_VERSION_ATLEAST(1, 2, 6)

        "MOUSEWHEEL_NORMAL",
        "MOUSEWHEEL_FLIPPED",

        {('Event', 'type'): [
            "KEYDOWN",
            "KEYUP",
            "MOUSEMOTION",
            "MOUSEBUTTONDOWN",
            "MOUSEBUTTONUP",
            "MOUSEWHEEL",
            "BUTTON_LEFT",
            "BUTTON_MIDDLE",
            "BUTTON_RIGHT",
            "JOYAXISMOTION",
            "JOYBALLMOTION",
            "JOYHATMOTION",
            "JOYBUTTONDOWN",
            "JOYBUTTONUP",
            "TEXTEDITING",
            "TEXTINPUT",
            "WINDOWEVENT",
            "QUIT",
            "SYSWMEVENT",
            "USEREVENT",
            "DROPFILE",
            "FINGERDOWN",
            "FINGERUP",
            "FINGERMOTION",
            "TEXTEDITING",
            "RENDER_TARGETS_RESET",
            "RENDER_DEVICE_RESET",
        ]},

        "TEXTINPUTEVENT_TEXT_SIZE",

        {('WindowEvent', 'event'): [
            'WINDOWEVENT_SHOWN',
            'WINDOWEVENT_HIDDEN',
            'WINDOWEVENT_EXPOSED',
            'WINDOWEVENT_MOVED',
            'WINDOWEVENT_RESIZED',
            'WINDOWEVENT_MINIMIZED',
            'WINDOWEVENT_MAXIMIZED',
            'WINDOWEVENT_RESTORED',
            'WINDOWEVENT_ENTER',
            'WINDOWEVENT_LEAVE',
            'WINDOWEVENT_FOCUS_GAINED',
            'WINDOWEVENT_FOCUS_LOST',
            'WINDOWEVENT_CLOSE',
            'WINDOWEVENT_SIZE_CHANGED',
        ]},

        "ADDEVENT",
        "PEEKEVENT",
        "GETEVENT",

        "HAT_CENTERED",
        "HAT_UP",
        "HAT_RIGHTUP",
        "HAT_RIGHT",
        "HAT_RIGHTDOWN",
        "HAT_DOWN",
        "HAT_LEFTDOWN",
        "HAT_LEFT",
        "HAT_LEFTUP",

        {('PixelFormat', 'format'): [
            "PIXELFORMAT_UNKNOWN",
            "PIXELFORMAT_INDEX1LSB",
            "PIXELFORMAT_INDEX1MSB",
            "PIXELFORMAT_INDEX4LSB",
            "PIXELFORMAT_INDEX4MSB",
            "PIXELFORMAT_INDEX8",
            "PIXELFORMAT_RGB332",
            "PIXELFORMAT_RGB444",
            "PIXELFORMAT_RGB555",
            "PIXELFORMAT_BGR555",
            "PIXELFORMAT_ARGB4444",
            "PIXELFORMAT_RGBA4444",
            "PIXELFORMAT_ABGR4444",
            "PIXELFORMAT_BGRA4444",
            "PIXELFORMAT_ARGB1555",
            "PIXELFORMAT_RGBA5551",
            "PIXELFORMAT_ABGR1555",
            "PIXELFORMAT_BGRA5551",
            "PIXELFORMAT_RGB565",
            "PIXELFORMAT_BGR565",
            "PIXELFORMAT_RGB24",
            "PIXELFORMAT_BGR24",
            "PIXELFORMAT_RGB888",
            "PIXELFORMAT_RGBX8888",
            "PIXELFORMAT_BGR888",
            "PIXELFORMAT_BGRX8888",
            "PIXELFORMAT_ARGB8888",
            "PIXELFORMAT_RGBA8888",
            "PIXELFORMAT_ABGR8888",
            "PIXELFORMAT_BGRA8888",
            "PIXELFORMAT_ARGB2101010",
            "PIXELFORMAT_YV12",
            "PIXELFORMAT_IYUV",
            "PIXELFORMAT_YUY2",
            "PIXELFORMAT_UYVY",
            "PIXELFORMAT_YVYU",
        ]},
        "BLENDMODE_NONE",
        "BLENDMODE_BLEND",
        "BLENDMODE_ADD",
        "BLENDMODE_MOD",

        "TEXTUREACCESS_STREAMING",

        "BLENDMODE_NONE",  # Rom; Additional constant
        "BLENDMODE_BLEND",  # Rom; Additional constant

        # the following ones are not exposed in Pygame
        "INIT_VIDEO",
        "INIT_EVERYTHING",  # Rom; Additional constant
        "BYTEORDER",
        "BIG_ENDIAN",
        "LIL_ENDIAN",
        ],

    '': [      # constants with no prefix in C
        "AUDIO_U8",
        "AUDIO_S8",
        "AUDIO_U16LSB",
        "AUDIO_S16LSB",
        "AUDIO_U16MSB",
        "AUDIO_S16MSB",
        "AUDIO_U16",
        "AUDIO_S16",
        "AUDIO_U16SYS",
        "AUDIO_S16SYS",

        "KMOD_NONE",
        "KMOD_LSHIFT",
        "KMOD_RSHIFT",
        "KMOD_LCTRL",
        "KMOD_RCTRL",
        "KMOD_LALT",
        "KMOD_RALT",
        "KMOD_LGUI",
        "KMOD_RGUI",
        "KMOD_NUM",
        "KMOD_CAPS",
        "KMOD_MODE",

        "KMOD_CTRL",
        "KMOD_SHIFT",
        "KMOD_ALT",
        "KMOD_GUI",
        ],

    'SDL': [      # constants with the 'SDL' prefix in C
        "K_UNKNOWN",
        "K_BACKSPACE",
        "K_TAB",
        "K_CLEAR",
        "K_RETURN",
        "K_PAUSE",
        "K_ESCAPE",
        "K_SPACE",
        "K_EXCLAIM",
        "K_QUOTEDBL",
        "K_HASH",
        "K_DOLLAR",
        "K_AMPERSAND",
        "K_QUOTE",
        "K_LEFTPAREN",
        "K_RIGHTPAREN",
        "K_ASTERISK",
        "K_PLUS",
        "K_COMMA",
        "K_MINUS",
        "K_PERIOD",
        "K_SLASH",
        "K_0",
        "K_1",
        "K_2",
        "K_3",
        "K_4",
        "K_5",
        "K_6",
        "K_7",
        "K_8",
        "K_9",
        "K_COLON",
        "K_SEMICOLON",
        "K_LESS",
        "K_EQUALS",
        "K_GREATER",
        "K_QUESTION",
        "K_AT",
        "K_LEFTBRACKET",
        "K_BACKSLASH",
        "K_RIGHTBRACKET",
        "K_CARET",
        "K_UNDERSCORE",
        "K_BACKQUOTE",
        "K_a",
        "K_b",
        "K_c",
        "K_d",
        "K_e",
        "K_f",
        "K_g",
        "K_h",
        "K_i",
        "K_j",
        "K_k",
        "K_l",
        "K_m",
        "K_n",
        "K_o",
        "K_p",
        "K_q",
        "K_r",
        "K_s",
        "K_t",
        "K_u",
        "K_v",
        "K_w",
        "K_x",
        "K_y",
        "K_z",
        "K_DELETE",

        "K_KP_0",
        "K_KP_1",
        "K_KP_2",
        "K_KP_3",
        "K_KP_4",
        "K_KP_5",
        "K_KP_6",
        "K_KP_7",
        "K_KP_8",
        "K_KP_9",
        "K_KP_PERIOD",
        "K_KP_DIVIDE",
        "K_KP_MULTIPLY",
        "K_KP_MINUS",
        "K_KP_PLUS",
        "K_KP_ENTER",
        "K_KP_EQUALS",
        "K_UP",
        "K_DOWN",
        "K_RIGHT",
        "K_LEFT",
        "K_INSERT",
        "K_HOME",
        "K_END",
        "K_PAGEUP",
        "K_PAGEDOWN",
        "K_F1",
        "K_F2",
        "K_F3",
        "K_F4",
        "K_F5",
        "K_F6",
        "K_F7",
        "K_F8",
        "K_F9",
        "K_F10",
        "K_F11",
        "K_F12",
        "K_F13",
        "K_F14",
        "K_F15",

        "K_NUMLOCKCLEAR",
        "K_CAPSLOCK",
        "K_SCROLLLOCK",
        "K_RSHIFT",
        "K_LSHIFT",
        "K_RCTRL",
        "K_LCTRL",
        "K_RALT",
        "K_LALT",
        "K_RGUI",
        "K_LGUI",
        "K_MODE",

        "K_HELP",
        "K_PRINTSCREEN",
        "K_SYSREQ",
        "K_MENU",
        "K_POWER",
        ],
    }
